- hosts: mysql
  become: yes
  become_method: sudo
  gather_facts: true
   tasks:  
     - name: Download sources Mysql
         get_url:
         url: http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
         dest: /opt/mysql

   - name: Install package for mysql
     yum:
       name: /opt/mysql/mysql-community-release-el7-5.noarch.rpm
       state: present


   - name: Install MySQL
     yum: name=mysql-server state=installed
     
     
     
     
